export const FETCH_REPOSITORIES = 'app/FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'app/FETCH_REPOSITORIES_SUCCESS'
export const FETCH_REPOSITORIES_FAIL = 'app/FETCH_REPOSITORIES_FAIL'

