export const FETCH_REPOS_BRUNCHES = 'brunches/FETCH_REPOS_BRUNCHES'
export const FETCH_REPOS_BRUNCHES_SUCCESS = 'brunches/FETCH_REPOS_BRUNCHES_SUCCESS'
export const FETCH_REPOS_BRUNCHES_FAIL = 'brunches/FETCH_REPOS_BRUNCHES_FAIL'

